#! usr/bin/bash

function mkd() {
	mkdir -p "$@" && cd "$_";
}

function h() {
	if [ -z "$*" ]; then
		history;
	else
		history | egrep "$@";
	fi;
}

function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* *;
	fi;
}

function calc() {
	local result="";
	result="$(printf "scale=10;$*\n" | bc --mathlib | tr -d '\\\n')";
	#                       └─ default (when `--mathlib` is used) is 20
	#
	if [[ "$result" == *.*  ]]; then
	# improve the output for decimal numbers
		printf "$result" |
			sed -e 's/^\./0./'    `# add "0" for cases like ".5"` \
			-e 's/^-\./-0./'      `# add "0" for cases like "-.5"`\
			-e 's/0*$//;s/\.$//';  # remove trailing zeros
	else
		printf "$result";
	fi;
	printf "\n";
}

function cl() {
	pygmentize -g "$1"| less -R;
}

# Extract archives - use: extract <file>
# Credits to http://dotfiles.org/~pseup/.bashrc
function extract() {
	if [ -f $1 ] ; then
		name="${$(basename $1)%.*}";

		case $1 in
			*.tar.bz2) tar xjf $1 ;;
			*.tar.gz) tar xzf $1 ;;
			*.bz2) bunzip2 $1 ;;
			*.rar) unrar x $1 ;;
			*.gz) gunzip $1 ;;
			*.tar) tar xf $1 ;;
			*.tbz2) tar xjf $1 ;;
			*.tgz) tar xzf $1 ;;
			*.zip) unzip $1 -d $name;;
			*.Z) uncompress $1 ;;
			*.7z) 7z x $1 ;;
			*) echo "'$1' cannot be extracted via extract()" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}

function dark() {
	if [ "$THEMECOLOUR" = "light" ]; then
		echo -e "\033]50;SetProfile=Default\a"
		export THEMECOLOUR=dark;
	else
		echo -e "\033]50;SetProfile=Light\a"
		export THEMECOLOUR=light;
	fi
}
